spring:
  application:
      name: license-config-server
  profiles:
      active: native,git,vault
  cloud:
      config:
        server:
          native:
            search-locations: classpath:/config
          git:
            uri: https://github.com/Kekcoe/config.git
            defaultLabel: master
            searchPaths: licensingservice
          vault:
            port: 8200
            host: 127.0.0.1
            kvVersion: 2
server:
  port: 8071

encrypt:
  key: secretkey