spring:
  application:
      name: license-config-server
  profiles:
      active: native,git
  cloud:
      config:
        server:
          native:
            search-locations: classpath:/config
          git:
            uri: https://github.com/Kekcoe/config.git
            defaultLabel: master
            searchPaths: licensingservice
server:
  port: 8071