spring:
  application:
      name: license-config-server
  profiles:
      active: native,git
  cloud:
      config:
        server:
          native:
            search-locations: classpath:/config
            git:
          searchPaths: licensingservice
server:
  port: 8071