spring:
  application:
      name: license-config-server
  profiles:
      active: native
#  cloud:
#      config:
#        server:
#          native:
#            search-locations: classpath:/config
#          bootstrap: false
server:
  port: 8071